name: Run algolia dockersearch

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        echo "APPLICATION_ID=$APPLICATION_ID" >> .env
        echo "API_KEY=$API_KEY" >> .env
        chmod +x ./bin/crawl.sh
        ./bin/crawl.sh
      env:
        APPLICATION_ID: ${{ secrets.ALGOLIA_DOCSEARCH_APP_ID }}
        API_KEY: ${{ secrets.ALGOLIA_DOCSEARCH_API_KEY }}